#!/usr/bin/env bash
# <Script Name>
# <Description what this module does>
# Written by <Author>
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot

# Unpack root at the end, so files are modified before
unpack /filesystem/root /

apt-get update
apt-get install -y avahi-daemon
apt-get clean
